name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: BananoStand CI
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome103-ff102
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cypress Tests
        shell: bash
        run: yarn && yarn cytest

